version: '3.9'

services:
  flask_api:
    build:
      context: ./flask_api  # Caminho relativo para o Dockerfile e arquivos da API
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - MICRO_QR_SERVICE_URL=http://microservico_qr:5000
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - microservico_qr
      - rabbitmq
    volumes:
      - ./flask_api_data:/data

  microservico_qr:
    build:
      context: ./microservico-qr  # Caminho relativo para o Dockerfile e arquivos do micro serviço
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - RABBITMQ_URL=amqp://rabbitmq
    depends_on:
      - rabbitmq
    volumes:
      - ./microservico_qr_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"    # Porta padrão para o RabbitMQ
      - "15672:15672"  # Porta da interface de gerenciamento do RabbitMQ
volumes:
  rabbitmq_data:
  flask_api_data:
  microservico_qr_data:
